name: CI - E-Market MERN API

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd mongosh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      NODE_ENV: test
      DB_URI: mongodb://localhost:27017/E_Market_API_Test
      JWT_SECRET: your-test-jwt-secret-change-in-production
      JWT_EXPIRE: 30m
      # Add any other required environment variables

    steps:
      # checkout repo
      - name: checkout code
        uses: actions/checkout@v4

      # install Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # install dependencies form package.json cleanly
      - name: Install dependencies
        run: npm ci
      
      # Wait for MongoDB to be ready
      - name: Wait for MongoDB
        run: |
          # Install mongosh (MongoDB Shell) for health checks
          curl -fsSL https://pgp.mongodb.com/server-7.0.asc | sudo gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg --dearmor
          echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-mongosh
          
          # Wait for MongoDB connection
          until mongosh --eval "db.adminCommand('ping')" localhost:27017/test --quiet; do
            echo "Waiting for MongoDB..."
            sleep 2
          done
          echo "MongoDB is ready!"
      
      # Create test environment file
      - name: Create test environment file
        run: |
          cat > .env.test << EOF
          NODE_ENV=test
          DB_URI=mongodb://localhost:27017/E_Market_API_Test
          JWT_SECRET=your-test-jwt-secret-change-in-production
          JWT_EXPIRE=30m
          PORT=3000
          # Add any other environment variables your app needs
          EOF
      
      # run all tests
      - name: Run tests
        run: npm run test

      # run coverage test
      - name: Run coverage test
        run: npm run coverage
      
      # Verify the Dockerfile builds successfully
      - name: Build Docker image
        run: docker build -t mern-api-image .